# Generated by Django 4.0 on 2021-12-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webbookmark',
            name='owner',
        ),
    ]
